<a href="https://colab.research.google.com/github/VijayTaori/Locating-the-null-values/blob/main/Cleaning_data_for_null_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [59]:
# Load the Excel file.
df_all = pd.read_excel('Crypto_2022_2021_2020 (Autosaved).xlsx',sheet_name='2020_2021_2022_ALL',index_col=0)
df_all.head()

,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type,ISIN,Notes
0.0,2.325392e+09,Buy Songbird,0.15,11.510000,16/11/2022 16:35:46,02/12/2022 12:29:02,1.0,0.00,0.00,0.01,0.01,0.0,0.00,0.0,-,Crypto,NaN,NaN
1.0,1.354685e+09,Buy Bitcoin,438.64,0.006812,19/10/2021 20:54:00,12/05/2022 09:16:36,1.0,3.82,-249.40,64396.26,27784.81,0.0,0.01,0.0,-,Crypto,NaN,NaN
2.0,1.361963e+09,Buy Bitcoin,94.37,0.001490,25/10/2021 19:00:27,12/05/2022 09:16:32,1.0,0.84,-52.98,63355.46,27799.73,0.0,0.01,0.0,-,Crypto,NaN,NaN
3.0,1.353187e+09,Buy Bitcoin,100.00,0.001611,18/10/2021 21:47:56,12/05/2022 09:16:29,1.0,0.91,-55.21,62087.07,27816.47,0.0,0.01,0.0,-,Crypto,NaN,NaN
4.0,1.370705e+09,Buy Bitcoin,397.37,0.006407,01/11/2021 11:59:53,12/05/2022 09:16:27,1.0,3.61,-218.86,62022.88,27862.74,0.0,0.01,0.0,-,Crypto,NaN,NaN

In [ ]:
# Lets find if there are null values in dataframe
print(df_all.shape) 
print(df_all.dropna(axis=0).shape) # number of rows that donot have null values
print(df_all.dropna(axis=1).shape) # number of columns that donot have null values

In [74]:
# Let's check if there are any columns with all null values
columns = df_all.columns
print(columns)

Index(['Position ID', 'Action', 'Amount', 'Units', 'Open Date', 'Close Date',
       'Leverage', 'Spread', 'Profit', 'Open Rate', 'Close Rate',
       'Take profit rate', 'Stop lose rate', 'Rollover Fees and Dividends',
       'Copied From', 'Type', 'ISIN', 'Notes'],
      dtype='object')

In [72]:
# Code to get individual number of null values in a column and its location
print(len(np.where(df_all.isna()['ISIN'])[0]))
np.where(df_all.isna()['Amount'])[0]

820

array([416, 467, 586])

In [76]:
# Let's write a function which will apply on the each coulmn 
def find_null_values(column_name):
  print('The number of null values in column {} are:'.format(column_name),len(np.where(df_all.isna()[column_name])[0]))
  print('And their integer location is:', np.where(df_all.isna()[column_name])[0])

In [77]:
# Execute the funtion
null_values_and_their_integer_location_in_df_all = [find_null_values(y) for y in columns]

The number of null values in column Position ID are: 3
And their integer location is: [416 467 586]
The number of null values in column Action are: 3
And their integer location is: [416 467 586]
The number of null values in column Amount are: 3
And their integer location is: [416 467 586]
The number of null values in column Units are: 3
And their integer location is: [416 467 586]
The number of null values in column Open Date are: 3
And their integer location is: [416 467 586]
The number of null values in column Close Date are: 3
And their integer location is: [416 467 586]
The number of null values in column Leverage are: 3
And their integer location is: [416 467 586]
The number of null values in column Spread are: 3
And their integer location is: [416 467 586]
The number of null values in column Profit are: 2
And their integer location is: [416 586]
The number of null values in column Open Rate are: 3
And their integer location is: [416 467 586]
The number of null values in column Close Rate are: 2
And their integer location is: [467 586]
The number of null values in column Take profit rate are: 3
And their integer location is: [416 467 586]
The number of null values in column Stop lose rate are: 3
And their integer location is: [416 467 586]
The number of null values in column Rollover Fees and Dividends are: 3
And their integer location is: [416 467 586]
The number of null values in column Copied From are: 2
And their integer location is: [467 586]
The number of null values in column Type are: 3
And their integer location is: [416 467 586]
The number of null values in column ISIN are: 820
And their integer location is: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819]
The number of null values in column Notes are: 820
And their integer location is: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819]

In [80]:
# Let's drop 'ISIN' and 'Notes' as all the values in these columns are null
# df_all.drop(['ISIN', 'Notes'],axis=1,inplace=True)

In [82]:
# Let's check if these columns are deleted
df_all.transpose() # We could also call the columns ---> df_all.columns

,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,341.0,342.0,343.0,344.0,345.0,346.0,347.0,348.0,349.0,350.0
Position ID,2325392242.0,1354684971.0,1361963252.0,1353186945.0,1370705010.0,1368128599.0,1345561924.0,1345562021.0,1283235754.0,1323686487.0,...,618615419.0,618615893.0,618680891.0,606923811.0,605782077.0,606873737.0,604775460.0,618618183.0,624654130.0,618620188.0
Action,Buy Songbird,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,Buy Bitcoin,...,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP,Buy XRP
Amount,0.15,438.64,94.37,100.0,397.37,782.56,157.74,811.09,2067.0,1003.0,...,25.0,25.0,80.0,25.0,25.0,25.0,25.0,50.0,25.0,25.0
Units,11.51,0.006812,0.00149,0.001611,0.006407,0.012804,0.002744,0.014125,0.042603,0.022772,...,119.38873,122.249389,400.4004,126.582278,127.291242,127.877238,131.440589,263.157895,126.518219,126.518219
Open Date,16/11/2022 16:35:46,19/10/2021 20:54:00,25/10/2021 19:00:27,18/10/2021 21:47:56,01/11/2021 11:59:53,29/10/2021 09:51:32,11/10/2021 21:51:38,11/10/2021 21:52:35,22/08/2021 20:36:09,27/09/2021 08:27:05,...,10/05/2020 00:15:38,10/05/2020 00:17:26,10/05/2020 06:53:27,25/04/2020 13:21:20,23/04/2020 16:55:28,24/04/2020 19:20:38,22/04/2020 20:47:13,10/05/2020 00:20:33,15/05/2020 21:11:01,10/05/2020 00:23:22
Close Date,02/12/2022 12:29:02,12/05/2022 09:16:36,12/05/2022 09:16:32,12/05/2022 09:16:29,12/05/2022 09:16:27,12/05/2022 09:16:23,12/05/2022 09:16:20,12/05/2022 09:16:16,12/05/2022 09:16:13,12/05/2022 09:16:10,...,20/05/2020 12:38:28,20/05/2020 12:37:31,17/05/2020 07:02:35,17/05/2020 07:02:24,17/05/2020 07:02:17,17/05/2020 07:02:05,17/05/2020 07:01:56,17/05/2020 07:01:47,16/05/2020 13:01:32,15/05/2020 03:32:44
Leverage,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Spread,0.0,3.82,0.84,0.91,3.61,7.21,1.54,7.95,23.98,12.81,...,0.6,0.62,2.0,0.63,0.63,0.64,0.66,1.31,0.62,0.62
Profit,0.0,-249.4,-52.98,-55.21,-218.86,-425.77,-81.27,-417.5,-880.08,-368.97,...,-0.75,-0.17,0.96,0.58,0.73,0.83,1.42,2.89,0.13,0.08
Open Rate,0.01,64396.26,63355.46,62087.07,62022.88,61119.72,57475.57,57422.57,48517.73,44045.69,...,0.21,0.2,0.2,0.2,0.2,0.2,0.19,0.19,0.2,0.2
Close Rate,0.01,27784.81,27799.73,27816.47,27862.74,27867.01,27860.01,27865.07,27860.06,27842.87,...,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
Take profit rate,0.0,0.0,0.0,0.0,0.0,0.0,632235.45,631320.25,533694.83,484498.88,...,2.3,2.25,2.2,2.17,2.16,2.15,2.09,2.09,2.17,2.17
Stop lose rate,0.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rollover Fees and Dividends,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Copied From,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
Type,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,...,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto,Crypto

In [88]:
# df_all.reset_index(inplace=True)
# The index was reset because it was not consistent

In [89]:
# Let's check out the rows of remaining null values at location 416, 467, 586
df_all.iloc[[416, 467, 586]]

,index,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type
416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,crypto,NaN,NaN,NaN,23,NaN
467,346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4438.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
# As index was reset the earlier index needs to deleted from columns
#df_all.drop('index',axis=1,inplace=True)

In [92]:
# Drop the rows of null values
df_all.drop([416,467,586],axis=0).iloc[[416, 467, 586]]

,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type
417,908928445.0,Buy Ethereum,84.45,0.064611,20/01/2021 10:11:54,24/01/2021 20:28:33,1.0,1.64,1.20,1307.06,1325.64,0.00,0.00,0.0,-,Crypto
469,767030099.0,Buy Bitcoin,25.00,0.001935,22/10/2020 12:56:12,16/11/2020 20:57:51,1.0,0.24,7.48,12921.66,16786.25,142120.63,0.01,0.0,-,Crypto
589,743239356.0,Buy Cardano,44.00,440.881764,29/09/2020 16:28:03,15/10/2020 09:58:32,1.0,1.63,1.63,0.10,0.1,1.10,0.00,0.0,-,Crypto

In [93]:
#df_all.drop([416,467,586],axis=0,inplace=True)

In [94]:
print(df_all.shape)
df_all.tail()

(817, 16)

,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type
815,606873737.0,Buy XRP,25.0,127.877238,24/04/2020 19:20:38,17/05/2020 07:02:05,1.0,0.64,0.83,0.20,0.2,2.15,0.0,0.0,-,Crypto
816,604775460.0,Buy XRP,25.0,131.440589,22/04/2020 20:47:13,17/05/2020 07:01:56,1.0,0.66,1.42,0.19,0.2,2.09,0.0,0.0,-,Crypto
817,618618183.0,Buy XRP,50.0,263.157895,10/05/2020 00:20:33,17/05/2020 07:01:47,1.0,1.31,2.89,0.19,0.2,2.09,0.0,0.0,-,Crypto
818,624654130.0,Buy XRP,25.0,126.518219,15/05/2020 21:11:01,16/05/2020 13:01:32,1.0,0.62,0.13,0.20,0.2,2.17,0.0,0.0,-,Crypto
819,618620188.0,Buy XRP,25.0,126.518219,10/05/2020 00:23:22,15/05/2020 03:32:44,1.0,0.62,0.08,0.20,0.2,2.17,0.0,0.0,-,Crypto

In [95]:
df_all.reset_index()

,index,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type
0,0,2.325392e+09,Buy Songbird,0.15,11.510000,16/11/2022 16:35:46,02/12/2022 12:29:02,1.0,0.00,0.00,0.01,0.01,0.00,0.00,0.0,-,Crypto
1,1,1.354685e+09,Buy Bitcoin,438.64,0.006812,19/10/2021 20:54:00,12/05/2022 09:16:36,1.0,3.82,-249.40,64396.26,27784.81,0.00,0.01,0.0,-,Crypto
2,2,1.361963e+09,Buy Bitcoin,94.37,0.001490,25/10/2021 19:00:27,12/05/2022 09:16:32,1.0,0.84,-52.98,63355.46,27799.73,0.00,0.01,0.0,-,Crypto
3,3,1.353187e+09,Buy Bitcoin,100.00,0.001611,18/10/2021 21:47:56,12/05/2022 09:16:29,1.0,0.91,-55.21,62087.07,27816.47,0.00,0.01,0.0,-,Crypto
4,4,1.370705e+09,Buy Bitcoin,397.37,0.006407,01/11/2021 11:59:53,12/05/2022 09:16:27,1.0,3.61,-218.86,62022.88,27862.74,0.00,0.01,0.0,-,Crypto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,815,6.068737e+08,Buy XRP,25.00,127.877238,24/04/2020 19:20:38,17/05/2020 07:02:05,1.0,0.64,0.83,0.20,0.2,2.15,0.00,0.0,-,Crypto
813,816,6.047755e+08,Buy XRP,25.00,131.440589,22/04/2020 20:47:13,17/05/2020 07:01:56,1.0,0.66,1.42,0.19,0.2,2.09,0.00,0.0,-,Crypto
814,817,6.186182e+08,Buy XRP,50.00,263.157895,10/05/2020 00:20:33,17/05/2020 07:01:47,1.0,1.31,2.89,0.19,0.2,2.09,0.00,0.0,-,Crypto
815,818,6.246541e+08,Buy XRP,25.00,126.518219,15/05/2020 21:11:01,16/05/2020 13:01:32,1.0,0.62,0.13,0.20,0.2,2.17,0.00,0.0,-,Crypto
816,819,6.186202e+08,Buy XRP,25.00,126.518219,10/05/2020 00:23:22,15/05/2020 03:32:44,1.0,0.62,0.08,0.20,0.2,2.17,0.00,0.0,-,Crypto

In [96]:
#df_all.reset_index(inplace=True)
#df_all.drop('index',axis=1,inplace=True)

In [97]:
print(df_all.shape)
df_all.tail()

(817, 16)

,Position ID,Action,Amount,Units,Open Date,Close Date,Leverage,Spread,Profit,Open Rate,Close Rate,Take profit rate,Stop lose rate,Rollover Fees and Dividends,Copied From,Type
812,606873737.0,Buy XRP,25.0,127.877238,24/04/2020 19:20:38,17/05/2020 07:02:05,1.0,0.64,0.83,0.20,0.2,2.15,0.0,0.0,-,Crypto
813,604775460.0,Buy XRP,25.0,131.440589,22/04/2020 20:47:13,17/05/2020 07:01:56,1.0,0.66,1.42,0.19,0.2,2.09,0.0,0.0,-,Crypto
814,618618183.0,Buy XRP,50.0,263.157895,10/05/2020 00:20:33,17/05/2020 07:01:47,1.0,1.31,2.89,0.19,0.2,2.09,0.0,0.0,-,Crypto
815,624654130.0,Buy XRP,25.0,126.518219,15/05/2020 21:11:01,16/05/2020 13:01:32,1.0,0.62,0.13,0.20,0.2,2.17,0.0,0.0,-,Crypto
816,618620188.0,Buy XRP,25.0,126.518219,10/05/2020 00:23:22,15/05/2020 03:32:44,1.0,0.62,0.08,0.20,0.2,2.17,0.0,0.0,-,Crypto

In [99]:
np.where(df_all.isna()) # No null values

(array([], dtype=int64), array([], dtype=int64))

In [100]:
df_all.to_excel('crypto_all.xlsx',sheet_name='2022_2021_2020')